apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-build
spec:
  params:
    - name: REPO
    - name: IMAGE
    - name: TAG
    - name: DOCKERFILE
  workspaces:
    - name: workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: $(params.REPO)
        - name: deleteExisting
          value: "true"
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)"
        - name: FORMAT
          value: "docker"
        - name: DOCKERFILE
          value: "$(params.DOCKERFILE)"